{% set name = "reikna" %}
{% set version = "0.9.0" %}
{% set sha256 = "bb322818290820d8263beaf4bc0ce68a14b5e065afe7281a90ccf7b4a206df30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.6,<3|>=3.2
    - pip

  run:
    - python >=2.6,<3|>=3.2
    - mako >=1.0.0
    - numpy >=2.0.0
    - funcsigs >=1.0.0
    # Optional
    # - pycuda
    # - pyopencl

test:
  imports:
    - reikna
    - reikna.algorithms
    - reikna.cbrng
    - reikna.cluda
    - reikna.core
    - reikna.fft
    - reikna.helpers
    - reikna.linalg

about:
  home: http://github.com/fjarri/reikna
  license: MIT
  license_file: LICENSE.txt
  summary: GPGPU algorithms for PyCUDA and PyOpenCL

  doc_url: http://reikna.publicfields.net/
  dev_url: https://github.com/fjarri/reikna

extra:
  recipe-maintainers:
    - jakirkham
