{% set name = "reikna" %}
{% set version = "0.7.5" %}
{% set sha256 = "d01f4264c8379ef2962a93aacb002d491b92ef9b5b22b45f77e7821dfa87bef7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - mako >=0.8.0
    - numpy >=1.6.0
    - funcsigs >=0.3
    # Optional
    # - pycuda
    # - pyopencl

test:
  imports:
    - reikna
    - reikna.algorithms
    - reikna.cbrng
    - reikna.cluda
    - reikna.core
    - reikna.fft
    - reikna.helpers
    - reikna.linalg

about:
  home: http://github.com/fjarri/reikna
  license: MIT
  license_file: LICENSE.txt
  summary: GPGPU algorithms for PyCUDA and PyOpenCL

  doc_url: http://reikna.publicfields.net/
  dev_url: https://github.com/fjarri/reikna

extra:
  recipe-maintainers:
    - jakirkham
